CREATE TABLE wp_posts (
    ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    post_author BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
    post_date DATETIME NOT NULL,
    post_date_gmt DATETIME NOT NULL,
    post_content LONGTEXT NOT NULL,
    post_title TEXT NOT NULL,
    post_excerpt TEXT NOT NULL,
    post_status VARCHAR(20) NOT NULL DEFAULT 'publish',
    comment_status VARCHAR(20) NOT NULL DEFAULT 'open',
    ping_status VARCHAR(20) NOT NULL DEFAULT 'open',
    post_password VARCHAR(255) NOT NULL DEFAULT '',
    post_name VARCHAR(200) NOT NULL DEFAULT '',
    to_ping TEXT NOT NULL,
    pinged TEXT NOT NULL,
    post_modified DATETIME NOT NULL,
    post_modified_gmt DATETIME NOT NULL,
    post_content_filtered LONGTEXT NOT NULL,
    post_parent BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
    guid VARCHAR(255) NOT NULL,
    menu_order INT(11) NOT NULL DEFAULT 0,
    post_type VARCHAR(20) NOT NULL,
    post_mime_type VARCHAR(100) NOT NULL,
    comment_count BIGINT(20) NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    KEY post_name (post_name(191)),
    KEY type_status_date (post_type, post_status, post_date, ID),
    KEY post_parent (post_parent),
    KEY post_author (post_author)
);
